window.GALLERY = [
{f:"fb-photo-7.jpg",c:"produkte",af:"Verjaarsdag-geskenkstel: wyn, nuwigheid-vadoek en ’n mooi strik.",en:"Birthday gift set: wine, a novelty tea towel and a pretty bow."},
{f:"fb-photo-8.jpg",c:"produkte",af:"“It’s Your Birthday!” — wyn en vadoek, reg vir die partytjie.",en:"“It’s Your Birthday!” — wine and tea towel, ready for the party."},
{f:"fb-photo-9.jpg",c:"produkte",af:"“I cook as good as I look” — potlap-en-vadoekstel.",en:"“I cook as good as I look” — pot holder and tea towel set."},
{f:"fb-photo-10.jpg",c:"produkte",af:"Volledige kombuis-stel met gepersonaliseerde bamboes-snyplank.",en:"Complete kitchen set with a personalised bamboo cutting board."},
{f:"fb-photo-14.jpg",c:"produkte",af:"Bamboes-snyplank “The Righteous man walks in His integrity” — spesiale bestelling vir Chrisma Fellowship.",en:"Bamboo cutting board “The Righteous man walks in His integrity” — a special order for Chrisma Fellowship."},
{f:"fb-photo-15.jpg",c:"produkte",af:"Kombuis-bederf: “I cook as good as I look” potlappe, nuwigheid-vadoek en verjaarsdagwyn.",en:"Kitchen treats: “I cook as good as I look” pot holders, a novelty tea towel and birthday wine."},
{f:"fb-photo-16.jpg",c:"produkte",af:"Volledige kombuisstel — snyplank, wyn, vadoeke en potlappe.",en:"Complete kitchen set — cutting board, wine, tea towels and pot holders."},
{f:"fb-photo-17.jpg",c:"produkte",af:"Nabyskoot van die “No bitchin’ in my kitchen” bamboes-snyplank met bypassende vadoek.",en:"Close-up of the “No bitchin’ in my kitchen” bamboo cutting board with matching tea towel."},
{f:"fb-photo-18.jpg",c:"produkte",af:"“It’s your birthday you can wine if you want” — verjaarsdagwyn op ’n snyplank.",en:"“It’s your birthday you can wine if you want” — birthday wine on a cutting board."},
{f:"fb-photo-19.jpg",c:"produkte",af:"Die volledige kombuis-geskenkstel netjies uitgepak.",en:"The complete kitchen gift set neatly laid out."},
{f:"fb-photo-34.jpg",c:"produkte",af:"Babavoetjie-sleutelhangers met Elihandro se geboortestatistieke.",en:"Baby-feet keyrings with Elihandro’s birth statistics."},
{f:"fb-photo-35.jpg",c:"produkte",af:"Houtskinkbord met ’n familie-fotocollage.",en:"Wooden serving tray with a family photo collage."},
{f:"fb-photo-37.jpg",c:"produkte",af:"Protea-skinkbord — “God is within her, she will not fall”.",en:"Protea tray — “God is within her, she will not fall”."},
{f:"fb-photo-41.jpg",c:"produkte",af:"Toegedraaide gepersonaliseerde bekers — dankie vir die pragtige resensie, SARS JHB!",en:"Wrapped personalised mugs — thank you for the lovely review, SARS JHB!"},
{f:"fb-photo-44.jpg",c:"produkte",af:"Veldblom-tumblers met handvatsels vir Tarika en Linda.",en:"Wildflower tumblers with handles for Tarika and Linda."},
{f:"fb-photo-60.jpg",c:"produkte",af:"Ons eie Bederf Jouself handelsmerk-sleutelhanger.",en:"Our own Bederf Jouself branded keyring."},
{f:"fb-photo-73.jpg",c:"produkte",af:"Protea-tumbler gepersonaliseer met die naam Florence.",en:"Protea tumbler personalised with the name Florence."},
{f:"fb-photo-74.jpg",c:"produkte",af:"Die agterkant van die protea-tumbler se ontwerp.",en:"The back of the protea tumbler design."},
{f:"fb-photo-75.jpg",c:"produkte",af:"Apteker-karikatuur op ’n gepersonaliseerde beker.",en:"Pharmacist caricature on a personalised mug."},
{f:"fb-photo-76.jpg",c:"produkte",af:"Familie-karikatuur fotobeker — ’n unieke aandenking.",en:"Family caricature photo mug — a unique keepsake."},
{f:"fb-photo-77.jpg",c:"produkte",af:"Luiperddruk-grimeersak gepersonaliseer vir Key-Leigh.",en:"Leopard-print makeup bag personalised for Key-Leigh."},
{f:"fb-photo-79.jpg",c:"produkte",af:"Foto-motorlugverfrisser — “Get home safe I love you”.",en:"Photo car air freshener — “Get home safe I love you”."},
{f:"fb-photo-80.jpg",c:"produkte",af:"Familieportret-lugverfrisser met ’n reisgebed.",en:"Family portrait air freshener with a traveller’s prayer."},
{f:"fb-photo-81.jpg",c:"produkte",af:"Familieportret-beker met kruis-en-duif kunswerk.",en:"Family portrait mug with cross-and-dove artwork."},
{f:"fb-photo-85.jpg",c:"produkte",af:"“Mom Boss” karikatuur-kunswerk uit ons karakterbeeld-kompetisie.",en:"“Mom Boss” caricature artwork from our character image competition."},
{f:"fb-photo-86.jpg",c:"produkte",af:"Gegraveerde leer-2026-dagboek vir “Beste Juffrou Lallie”.",en:"Engraved leather 2026 diary for “Beste Juffrou Lallie”."},
{f:"fb-photo-87.jpg",c:"produkte",af:"Onderwyser-dagboeke vir Juffrou Amelia, Lallie en Anique, met sonneblom-sleutelhangers.",en:"Teacher diaries for Miss Amelia, Lallie and Anique, with sunflower keyrings."},
{f:"fb-photo-88.jpg",c:"produkte",af:"“little Angels” swart notaboeke met name, reg verpak.",en:"“little Angels” black notebooks with names, packed and ready."},
{f:"fb-photo-89.jpg",c:"produkte",af:"Naametiket-plakkers vir Milan Burger, saam met ’n eenhoring-sak.",en:"Name label stickers for Milan Burger, with a unicorn bag."},
{f:"fb-photo-90.jpg",c:"produkte",af:"Batman-naamplakkers vir Declan Burger — nabyskoot.",en:"Batman name stickers for Declan Burger — close-up."},
{f:"fb-photo-91.jpg",c:"produkte",af:"Panda-naamplakkers en sleutelhanger vir De’shané Giezen.",en:"Panda name stickers and keyring for De’shané Giezen."},
{f:"fb-photo-92.jpg",c:"produkte",af:"Naametiketvel vir Tanika de Wet.",en:"Name label sheet for Tanika de Wet."},
{f:"fb-photo-93.jpg",c:"produkte",af:"Skryfbehoeftes netjies gemerk met naamplakkers.",en:"Stationery neatly marked with name stickers."},
{f:"fb-photo-109.jpg",c:"produkte",af:"Pienk-en-swart gesublimeerde gholfhemp vir Inspirations Hair & Nail Studio.",en:"Pink-and-black sublimated golf shirt for Inspirations Hair & Nail Studio."},
{f:"fb-photo-110.jpg",c:"produkte",af:"Blou ATS-gholfhemp — 3D-voorstelling van die ontwerp.",en:"Blue ATS golf shirt — 3D mock-up of the design."},
{f:"fb-photo-111.jpg",c:"produkte",af:"Ons geweefde Bederf Jouself kledingetiket in ’n hemp.",en:"Our woven Bederf Jouself clothing label in a shirt."},
{f:"fb-photo-112.jpg",c:"produkte",af:"Jump Street “Dare to Jump” gholfhemde — werklike drukwerk.",en:"Jump Street “Dare to Jump” golf shirts — the real printed product."},
{f:"fb-photo-113.jpg",c:"produkte",af:"Korporatiewe hemde massaverpak en gereed vir aflewering.",en:"Corporate shirts bulk-packed and ready for delivery."},
{f:"fb-photo-125.jpg",c:"produkte",af:"“Kak met kalmte, gooi kole pappie!” — potlap en oondhandskoen.",en:"“Kak met kalmte, gooi kole pappie!” — pot holder and oven glove."},
{f:"fb-photo-126.jpg",c:"produkte",af:"Jump Street geborduurde logo — nabyskoot van die stikwerk.",en:"Jump Street embroidered logo — a close-up of the stitching."},
{f:"fb-photo-129.jpg",c:"produkte",af:"Blou Jump Street gholfhemp-voorstelling.",en:"Blue Jump Street golf shirt mock-up."},
{f:"fb-photo-130.jpg",c:"produkte",af:"Wit gholfhemp met pienk-en-blou verfspat vir Inspirations.",en:"White golf shirt with pink-and-blue paint splash for Inspirations."},
{f:"fb-photo-132.jpg",c:"produkte",af:"Ombre-tumblers gepersonaliseer vir Geraldine.",en:"Ombre tumblers personalised for Geraldine."},
{f:"fb-photo-133.jpg",c:"produkte",af:"Bolla-dame en sonneblom tumbler.",en:"Messy-bun lady and sunflower tumbler."},
{f:"fb-photo-134.jpg",c:"produkte",af:"John Deere-tumbler vir die plaas-liefhebber.",en:"John Deere tumbler for the farm lover."},
{f:"fb-photo-135.jpg",c:"produkte",af:"Verweerde John Deere tumbler-variant.",en:"Distressed John Deere tumbler variant."},
{f:"fb-photo-136.jpg",c:"produkte",af:"Veerpyltjie-tumbler en “Happy 10th anniversary Bertus” tumbler.",en:"Darts tumbler and “Happy 10th anniversary Bertus” tumbler."},
{f:"fb-photo-137.jpg",c:"produkte",af:"Kamoefleer-tumbler gepersonaliseer vir Ryno.",en:"Camouflage tumbler personalised for Ryno."},
{f:"fb-photo-138.jpg",c:"produkte",af:"Takbok-en-kamoefleer tumbler.",en:"Deer-and-camouflage tumbler."},
{f:"fb-photo-139.jpg",c:"produkte",af:"Rooi tumbler gepersonaliseer vir Francois.",en:"Red tumbler personalised for Francois."},
{f:"fb-photo-140.jpg",c:"produkte",af:"Buffelsfontein Brandewyn-etiket tumbler.",en:"Buffelsfontein Brandy label tumbler."},
{f:"fb-photo-142.jpg",c:"produkte",af:"Brandewyn-geskenkmandjie met Buffelsfontein, Mokate en Coke.",en:"Brandy gift basket with Buffelsfontein, Mokate and Coke."},
{f:"fb-photo-143.jpg",c:"produkte",af:"Miller Genuine Draft matglas-bierbeker en geskenke-collage.",en:"Miller Genuine Draft frosted beer mug and gift collage."},
{f:"fb-photo-144.jpg",c:"produkte",af:"Geskenkcollage met tumblers, gedrukte sokkies en die “Kosie se vuil Coke”-sakkie.",en:"Gift collage with tumblers, printed socks and the “Kosie se vuil Coke” bag."},
{f:"fb-photo-151.jpg",c:"produkte",af:"Waterbottels met die Chrisma Fellowship-logo.",en:"Water bottles with the Chrisma Fellowship logo."},
{f:"fb-photo-152.jpg",c:"produkte",af:"Rye “The Righteous” gedrukte aluminiumbottels — massabestelling vir die kerk.",en:"Rows of “The Righteous” printed aluminium bottles — a bulk order for the church."},
{f:"fb-photo-153.jpg",c:"produkte",af:"Geskenkbokse toegedraai met silwer strikke — massabestelling.",en:"Gift boxes wrapped with silver bows — a bulk order."},
{f:"fb-photo-154.jpg",c:"produkte",af:"Gepersonaliseerde sjokoladeplakke met strikke.",en:"Personalised chocolate slabs with bows."},
{f:"fb-photo-3.jpg",c:"sport",af:"Connor se persoonlike “Darts Bar” — baanloper, bekermatjies en botteloopmaker.",en:"Connor’s personalised “Darts Bar” — bar runner, coasters and bottle opener."},
{f:"fb-photo-4.jpg",c:"sport",af:"Magda se blink dart-blikkie — persoonlik gemaak, nes sy dit wou hê.",en:"Magda’s glittery dart tin — personalised just the way she wanted it."},
{f:"fb-photo-5.jpg",c:"sport",af:"Ryp bierbeker met dartbord-ontwerp — spesiaal vir Nathan.",en:"Frosted beer mug with a dartboard design — specially for Nathan."},
{f:"fb-photo-6.jpg",c:"sport",af:"Dartbord-sleutelhouers — klein bederfie, groot glimlag.",en:"Dartboard keyrings — a small treat, a big smile."},
{f:"fb-photo-11.jpg",c:"sport",af:"Hokkie-motorlugverfrisser vir Linda — “Vertrou op die Here met jou hele hart” (Spreuke 3:5).",en:"Hockey car air freshener for Linda — “Trust in the Lord with all your heart” (Proverbs 3:5)."},
{f:"fb-photo-12.jpg",c:"sport",af:"Swart hokkiestok-sak met bypassende gepersonaliseerde sak-etiket en karabynhaak.",en:"Black hockey stick bag with a matching personalised bag tag and carabiner."},
{f:"fb-photo-13.jpg",c:"sport",af:"Drie wit sportwaterbottels met hokkie-meisie kunswerk en skoolwapen.",en:"Three white sports water bottles with hockey-girl artwork and a school crest."},
{f:"fb-photo-20.jpg",c:"sport",af:"Vier veerpyltjiebord-bekermatjies saam met ’n koue bier.",en:"Four dartboard coasters with a cold beer."},
{f:"fb-photo-21.jpg",c:"sport",af:"Nabyskoot van die pers “little Angels” hemp-sakdruk.",en:"Close-up of the purple “little Angels” shirt pocket print."},
{f:"fb-photo-22.jpg",c:"sport",af:"Pers “Called to Life / little Angels” hemde in massa gedruk (Psalm 139:13).",en:"Purple “Called to Life / little Angels” shirts printed in bulk (Psalm 139:13)."},
{f:"fb-photo-39.jpg",c:"sport",af:"Action Netball waterbottels vir Deshane van die Midvaal Bumblebees.",en:"Action Netball water bottles for Deshane of the Midvaal Bumblebees."},
{f:"fb-photo-40.jpg",c:"sport",af:"Action Netball trektou-sak — 3D-voorstelling.",en:"Action Netball drawstring bag — 3D mock-up."},
{f:"fb-photo-46.jpg",c:"sport",af:"Gepersonaliseerde netbal-strikke in oranje en navy met spelername.",en:"Personalised netball bows in orange and navy with player names."},
{f:"fb-photo-47.jpg",c:"sport",af:"Skool-serpe: “Mnr Krappies & Krefies” en “Mej Vissie Junior” vir Laerskool A.G. Visser.",en:"School sashes: “Mnr Krappies & Krefies” and “Mej Vissie Junior” for Laerskool A.G. Visser."},
{f:"fb-photo-48.jpg",c:"sport",af:"Nabyskoot van ’n serp met die Laerskool A.G. Visser-wapen.",en:"Close-up of a sash with the Laerskool A.G. Visser crest."},
{f:"fb-photo-49.jpg",c:"sport",af:"Volledige stel gedrukte prefek-serpe — van Graad 2 tot Graad 6 Prins.",en:"Complete set of printed prefect sashes — from Grade 2 to Grade 6 Prince."},
{f:"fb-photo-50.jpg",c:"sport",af:"Sewe vlugbal-waterbottels, elkeen met sy eie naam.",en:"Seven volleyball water bottles, each with its own name."},
{f:"fb-photo-51.jpg",c:"sport",af:"Gepersonaliseerde vlugbal-sokkies waaiervormig uitgepak.",en:"Personalised volleyball socks fanned out."},
{f:"fb-photo-52.jpg",c:"sport",af:"Massabestelling swart duffelsakke met spelername en -nommers.",en:"Bulk order of black duffel bags with player names and numbers."},
{f:"fb-photo-53.jpg",c:"sport",af:"Netbal-waterbottel trio vir Mia, met skoolwapen.",en:"Netball water bottle trio for Mia, with a school crest."},
{f:"fb-photo-54.jpg",c:"sport",af:"Netbalbottel-paar vir Aviwe — “Net ’n meisie wat lief is vir netbal”.",en:"Netball bottle pair for Aviwe — “Just a girl who loves netball”."},
{f:"fb-photo-55.jpg",c:"sport",af:"’n Ry gepersonaliseerde netbalbottels — Angel, Danielle, Jane en meer.",en:"A row of personalised netball bottles — Angel, Danielle, Jane and more."},
{f:"fb-photo-56.jpg",c:"sport",af:"Netbalbottel in geel vir Melanie.",en:"Netball bottle in yellow for Melanie."},
{f:"fb-photo-59.jpg",c:"sport",af:"’n Hoop gepersonaliseerde rugbyseun-sleutelhangers met name.",en:"A pile of personalised rugby-boy keyrings with names."},
{f:"fb-photo-61.jpg",c:"sport",af:"Rugbyseun-sleutelhanger vir Dirk — nabyskoot.",en:"Rugby-boy keyring for Dirk — close-up."},
{f:"fb-photo-62.jpg",c:"sport",af:"O.11-rugbyspan se bestelling: sakke, rooi pette, sleutelhangers en wapens.",en:"The U11 rugby team’s order: bags, red caps, keyrings and badges."},
{f:"fb-photo-63.jpg",c:"sport",af:"Sleutelhangers en wapens in detail op die rugbysakke.",en:"Keyrings and badges in detail on the rugby bags."},
{f:"fb-photo-64.jpg",c:"sport",af:"Sleutelhangers vir Jandré en Luan, saam met Ruben se rooi pet.",en:"Keyrings for Jandré and Luan, with Ruben’s red cap."},
{f:"fb-photo-66.jpg",c:"sport",af:"“Rugby Lewe” waterverf-kunswerk met ’n seun se eie foto.",en:"“Rugby Lewe” watercolour artwork featuring a boy’s own photo."},
{f:"fb-photo-114.jpg",c:"sport",af:"Netbalfrokkie-voorstelling vir Janneke — busmotief met Psalm 144:1.",en:"Netball vest mock-up for Janneke — bus motif with Psalm 144:1."},
{f:"fb-photo-115.jpg",c:"sport",af:"Blomme-netbalfrokkie voorstelling vir Janneke (Filippense 4:13).",en:"Floral netball vest mock-up for Janneke (Philippians 4:13)."},
{f:"fb-photo-116.jpg",c:"sport",af:"Pers “Called to Life” spanhemp-voorstelling.",en:"Purple “Called to Life” team shirt mock-up."},
{f:"fb-photo-117.jpg",c:"sport",af:"Pienk-glitter spanhemde, verpak en gereed.",en:"Pink glitter team shirts, packed and ready."},
{f:"fb-photo-118.jpg",c:"sport",af:"Blomme-afrigterhemp voorstelling — “Janneke Coach”.",en:"Floral coach shirt mock-up — “Janneke Coach”."},
{f:"fb-photo-119.jpg",c:"sport",af:"“Fun Play Learn” frokkie-voorstelling.",en:"“Fun Play Learn” vest mock-up."},
{f:"fb-photo-120.jpg",c:"sport",af:"Gedrukte afrigterhemp “Hanri Coach — Fun Play Learn” — die werklike kledingstuk.",en:"Printed coach shirt “Hanri Coach — Fun Play Learn” — the actual garment."},
{f:"fb-photo-121.jpg",c:"sport",af:"Pienk verfspat-netbalhemp — werklike kledingstuk.",en:"Pink paint-splash netball shirt — the actual garment."},
{f:"fb-photo-122.jpg",c:"sport",af:"Midvaal Buffels veerpyltjie-gholfhemp met pers vlamme — Nationals 2025.",en:"Midvaal Buffels darts golf shirt with purple flames — Nationals 2025."},
{f:"fb-photo-123.jpg",c:"sport",af:"Midvaal Buffels veerpyltjie-gholfhemp met pienk vlamme.",en:"Midvaal Buffels darts golf shirt with pink flames."},
{f:"fb-photo-124.jpg",c:"sport",af:"“The Jackel” gholfhemp-voorstelling in swart en seegroen.",en:"“The Jackel” golf shirt mock-up in black and teal."},
{f:"fb-photo-127.jpg",c:"sport",af:"Midvaal Buffels veerpyltjiehemp vir Jacques — agterkant van die werklike hemp.",en:"Midvaal Buffels darts shirt for Jacques — back of the actual shirt."},
{f:"fb-photo-128.jpg",c:"sport",af:"Drie spelers trots in hul Midvaal Buffels-hemde.",en:"Three players proudly wearing their Midvaal Buffels shirts."},
{f:"fb-photo-131.jpg",c:"sport",af:"Leeu-en-veerpyltjiebord hemp-voorstelling vir Brad.",en:"Lion-and-dartboard shirt mock-up for Brad."},
{f:"fb-photo-145.jpg",c:"sport",af:"Pienk afrigter-T-hemp voorstelling — “Janneke Coach, Fun Play Learn”.",en:"Pink coach T-shirt mock-up — “Janneke Coach, Fun Play Learn”."},
{f:"fb-photo-146.jpg",c:"sport",af:"Werklike netbalfrokkie vir Janneke — “Fun Play Learn”.",en:"The actual netball vest for Janneke — “Fun Play Learn”."},
{f:"fb-photo-147.jpg",c:"sport",af:"Verfspat-netbalhemp vir Kaitlyn — Psalm 144:1.",en:"Paint-splash netball shirt for Kaitlyn — Psalm 144:1."},
{f:"fb-photo-148.jpg",c:"sport",af:"Blomme-netbalfrokkie — “Netball, Filippense 4:13”.",en:"Floral netball vest — “Netball, Philippians 4:13”."},
{f:"fb-photo-149.jpg",c:"sport",af:"Hokkie-kopband vir Linda — “Vertrou op die Here” — soos gedra.",en:"Hockey headband for Linda — “Trust in the Lord” — as worn."},
{f:"fb-photo-33.jpg",c:"feesdae",af:"Moedersdag-fotogeskenkstel: raam, kussing, beker en tumbler — vir ’n pragtige ma.",en:"Mother’s Day photo gift set: frame, cushion, mug and tumbler — for a beautiful mom."},
{f:"fb-photo-36.jpg",c:"feesdae",af:"“Happy Mother’s Day” foto-skinkbord met blomraampies.",en:"“Happy Mother’s Day” photo tray with floral frames."},
{f:"fb-photo-72.jpg",c:"feesdae",af:"Happy Easter geskenkboks met gepersonaliseerde beker en lekkers.",en:"Happy Easter gift box with a personalised mug and treats."},
{f:"fb-photo-82.jpg",c:"feesdae",af:"Valentynsdag “Survival Liefde Kit” met grappie-etikette en rooi strikke.",en:"Valentine’s Day “Survival Love Kit” with joke labels and red bows."},
{f:"fb-photo-83.jpg",c:"feesdae",af:"“Aan my Honey Bun” — Valentynsboks se voorkant.",en:"“To my Honey Bun” — the front of the Valentine’s box."},
{f:"fb-photo-84.jpg",c:"feesdae",af:"Valentynsdag Honey Bun-boks propvol lekkernye en etikette.",en:"Valentine’s Day Honey Bun box packed with treats and labels."},
{f:"fb-photo-94.jpg",c:"feesdae",af:"’n Stapel Kersfees-geskenkbokse met vinielbelettering.",en:"A stack of Christmas gift boxes with vinyl lettering."},
{f:"fb-photo-95.jpg",c:"feesdae",af:"Grinch-geskenkboks: beker, legkaart, kersmus en koekies.",en:"Grinch gift box: mug, puzzle, Christmas hat and cookies."},
{f:"fb-photo-96.jpg",c:"feesdae",af:"’n Piramide Grinch-kersbekers.",en:"A pyramid of Grinch Christmas mugs."},
{f:"fb-photo-97.jpg",c:"feesdae",af:"Foto-kersballe vir die kersboom.",en:"Photo baubles for the Christmas tree."},
{f:"fb-photo-98.jpg",c:"feesdae",af:"Gepersonaliseerde kersmus vir Tarika, met geskenkboks.",en:"Personalised Christmas hat for Tarika, with a gift box."},
{f:"fb-photo-99.jpg",c:"feesdae",af:"Merry Christmas geskenkboks met glitter-kersmusse.",en:"Merry Christmas gift box with glitter Christmas hats."},
{f:"fb-photo-100.jpg",c:"feesdae",af:"Kersman-gordel wynetiket — “He sees you when you’re drinking”.",en:"Santa-belt wine label — “He sees you when you’re drinking”."},
{f:"fb-photo-101.jpg",c:"feesdae",af:"Grinch-wynetikette vir die feestyd.",en:"Grinch wine labels for the festive season."},
{f:"fb-photo-102.jpg",c:"feesdae",af:"Merry Christmas T-hemde — ’n vrolike collage.",en:"Merry Christmas T-shirts — a cheerful collage."},
{f:"fb-photo-103.jpg",c:"feesdae",af:"“Daddy Clause / Mommy Clause” hemde met babavoetjies.",en:"“Daddy Clause / Mommy Clause” shirts with baby feet."},
{f:"fb-photo-104.jpg",c:"feesdae",af:"Grinch-sjokoladeomhulsels — klein feestelike bederfies.",en:"Grinch chocolate wrappers — small festive treats."},
{f:"fb-photo-105.jpg",c:"feesdae",af:"Kersvader-drasakke: “Maak oop op 25 Desember — Aan Bella/David van Kersvader”.",en:"Santa sacks: “Open on 25 December — To Bella/David from Father Christmas”."},
{f:"fb-photo-106.jpg",c:"feesdae",af:"Gepersonaliseerde kersgeskenk-etikette.",en:"Personalised Christmas gift tags."},
{f:"fb-photo-107.jpg",c:"feesdae",af:"“Grinchmas Eve Box” met toegedraaide lekkers.",en:"“Grinchmas Eve Box” with wrapped treats."},
{f:"fb-photo-108.jpg",c:"feesdae",af:"Grinchmas Eve Box — elf-omhulsel weergawe.",en:"Grinchmas Eve Box — elf wrapper version."},
{f:"fb-photo-141.jpg",c:"feesdae",af:"Vadersdag-geskenkcollage: telefoonstaanders, sokkies, oondhandskoene en “Ek louf you teveel”.",en:"Father’s Day gift collage: phone stands, socks, oven gloves and “Ek louf you teveel”."},
{f:"fb-photo-2.jpg",c:"promos",af:"Ons Vadersdag-kombo — hou ons Facebook-blad dop vir spesiale aanbiedinge!",en:"Our Father’s Day combo — keep an eye on our Facebook page for specials!"},
{f:"fb-photo-23.jpg",c:"promos",af:"Vadersdag Spesiaal R550 — kroegmat, handdoek, tumbler en sleutelring.",en:"Father’s Day Special R550 — bar mat, towel, tumbler and keyring."},
{f:"fb-photo-24.jpg",c:"promos",af:"“Warmth you can feel” — 2L-warmwaterbottel strooibiljet vir Vadersdag.",en:"“Warmth you can feel” — 2L hot water bottle flyer for Father’s Day."},
{f:"fb-photo-25.jpg",c:"promos",af:"Eksamen Anti-Stres Kit R150 — gepersonaliseerde potloodblikkie en sjokolade.",en:"Exam Anti-Stress Kit R150 — personalised pencil tin and chocolate."},
{f:"fb-photo-26.jpg",c:"promos",af:"Premium Canvas Prints — pryse van A5 tot A0, plus multi-pakke.",en:"Premium Canvas Prints — prices from A5 to A0, plus multi-packs."},
{f:"fb-photo-27.jpg",c:"promos",af:"“Warmth you can feel” warmwaterbottel-strooibiljet — ouma-weergawe.",en:"“Warmth you can feel” hot water bottle flyer — grandma version."},
{f:"fb-photo-28.jpg",c:"promos",af:"Vadersdag 20oz termiese tumblers R200 — “For Dad or Grandpa”.",en:"Father’s Day 20oz thermal tumblers R200 — “For Dad or Grandpa”."},
{f:"fb-photo-29.jpg",c:"promos",af:"Vadersdag foto-lessenaarmat R250 — strooibiljet.",en:"Father’s Day photo desk mat R250 — flyer."},
{f:"fb-photo-30.jpg",c:"promos",af:"Vadersdag-strooibiljet — “Celebrate his superpowers” met bekers en fotogeskenke.",en:"Father’s Day flyer — “Celebrate his superpowers” with mugs and photo gifts."},
{f:"fb-photo-31.jpg",c:"promos",af:"Vadersdag gereedskapstel — “Tool Set, the perfect gift”.",en:"Father’s Day tool set — “Tool Set, the perfect gift”."},
{f:"fb-photo-32.jpg",c:"promos",af:"Vadersdag koelersak — “Like a normal dad, but cooler”.",en:"Father’s Day cooler bag — “Like a normal dad, but cooler”."},
{f:"fb-photo-38.jpg",c:"promos",af:"“Hockey Gear made for champions” — bottels, hemde, sakke, strikke en sokkies.",en:"“Hockey Gear made for champions” — bottles, shirts, bags, bows and socks."},
{f:"fb-photo-42.jpg",c:"promos",af:"Mother’s Day Tray Gift R300 — strooibiljet.",en:"Mother’s Day Tray Gift R300 — flyer."},
{f:"fb-photo-43.jpg",c:"promos",af:"PU-leer foto-beursies — strooibiljet.",en:"PU leather photo wallets — flyer."},
{f:"fb-photo-45.jpg",c:"promos",af:"“Gelukkige Moedersdag” geskenkreeks: beker, kussing, bottel en sleutelring.",en:"“Happy Mother’s Day” gift range: mug, cushion, bottle and keyring."},
{f:"fb-photo-57.jpg",c:"promos",af:"Personalized Wedding Gifts — geskenke vir strooimeisies en strooijonkers.",en:"Personalized Wedding Gifts — gifts for bridesmaids and groomsmen."},
{f:"fb-photo-58.jpg",c:"promos",af:"Personalized Hockey Bottles — strooibiljet.",en:"Personalized Hockey Bottles — flyer."},
{f:"fb-photo-65.jpg",c:"promos",af:"“Personalized keyrings available” — advertensie.",en:"“Personalized keyrings available” — advert."},
{f:"fb-photo-67.jpg",c:"promos",af:"“Awesome Rugby Water Bottles” — advertensie.",en:"“Awesome Rugby Water Bottles” — advert."},
{f:"fb-photo-68.jpg",c:"promos",af:"“Personalised Netball water bottles for sale” — banier.",en:"“Personalised Netball water bottles for sale” — banner."},
{f:"fb-photo-69.jpg",c:"promos",af:"“Personalized Bottles Available” — All Stars Netball bottel vir Karli-Han.",en:"“Personalized Bottles Available” — All Stars Netball bottle for Karli-Han."},
{f:"fb-photo-70.jpg",c:"promos",af:"Fotokussing-strooibiljet — “Turn your memories into something special”.",en:"Photo cushion flyer — “Turn your memories into something special”."},
{f:"fb-photo-71.jpg",c:"promos",af:"“Personalize your own makeup bag” — advertensie.",en:"“Personalize your own makeup bag” — advert."},
{f:"fb-photo-78.jpg",c:"promos",af:"Motor-lugverfrissers met jou eie foto — “Drive safe we love you”.",en:"Car air fresheners with your own photo — “Drive safe we love you”."},
{f:"fb-photo-150.jpg",c:"promos",af:"Hokkietoerusting-strooibiljet (Meyerton): bottels, sportsakke, sleutelhangers en kopbande.",en:"Hockey gear flyer (Meyerton): bottles, sports bags, keyrings and headbands."}
];
